import Head from "next/head";
import { Inter } from "@next/font/google";
import axios from "axios";
import BarChart from "../components/charts/barchart";
import LineChart from "../components/charts/LineChart";
import PageVisits from "../components/charts/PageVisits";
import PieChart from "../components/charts/PieChart";
import NewsTable from "../components/charts/NewsTable";

const inter = Inter({ subsets: ["latin"] });

export default function Home({
  barchart,
  linechart,
  indicators,
  piechart,
  news,
}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <BarChart data={barchart} />
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <LineChart data={linechart} />
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        <PageVisits indicators={indicators} />
        <div>Surya</div>
        <div>Surya</div>
        <div>Surya</div>
        {/* <PieChart piechart={piechart} /> */}
        <NewsTable news={news} />
      </main>
    </>
  );
}

export const getStaticProps = async () => {
  const linechart = await axios.get("http://127.0.0.1:5000/AMZNlinechart");
  const barchart = await axios.get("http://127.0.0.1:5000/AMZNbarchart");
  const piechart = await axios.get("http://127.0.0.1:5000/AMZNpiechart");
  const news = await axios.get("http://127.0.0.1:5000/AMZNnews");
  const indicators = await axios.get("http://127.0.0.1:5000/AMZNindicators");
  // console.log(res);
  return {
    props: {
      linechart: linechart.data,
      barchart: barchart.data,
      piechart: piechart.data,
      news: news.data,
      indicators: indicators.data,
      //   piechart: piechart.data,
    },
  };
};
